### PR TITLE
Apply alphabetical sort of areas in project management screen

### LINKED ISSUE #245: Wrong order of areas in project management screen
In _Data management -> projects_ screen, when you create or edit a project, the combo box with the list of areas has no logical order. They should be sorted alphabetically.

### PR DESCRIPTION
**Pull request by tonythomas01**
Fix #245

### CODE REVIEW

**Comment by jaragunde** [comment]
Looks good! Just a silly request, could you amend the commit message to start with `[#245]`? We use that format in commits that fix some issue, like in: ecc4b5b

**Comment by tonythomas01** [comment]
Done!

**Comment by jaragunde** [comment]
I've just noticed the author header:
```
Author: tonythomas01 <01tonythomas@...>
```

You will probably want to let git use your real name and then amend the commit with:
```
git config --global user.name "John Doe"
git commit --amend --reset-author
```

**Comment by tonythomas01** [comment]
I did that, and now in my git log, I can see 

> Author: Tony Thomas <01tonythomas@gmail.com>

**Comment by jaragunde** [comment]
Merged! Thank you!

**Pull request merged**
