### PR TITLE
Add task deletion to task list

### PR DESCRIPTION
**Pull request by negreirosleo**
Clicking on the trashcan icon will call the task deletion endpoin

### Screenshots

[Screencast from 2023-11-14 13-18-43.webm](https://github.com/Igalia/phpreport/assets/20492786/9a95a1b3-88cc-428e-88fb-effaaeef8b90)

### CODE REVIEW

**Review by anarute — APPROVED** [review]
LGTM, thanks!

**Review by dmtrek14 — COMMENTED** [review]
@anarute Do we want there to be a confirmation for the deletion? The current app doesn't have a confirmation, but someone does have to delete, then save changes. So it could be nice to make sure someone really wants to delete.

**Comment by anarute** [comment]
> then save changes.

Not really because the current version has the autosave feature.  But agree we can add it as there's no undo.

**Review by dmtrek14 — APPROVED** [review]
Looks good here - thanks for the confirmation on delete!

**Review by anarute — APPROVED** [review]
Thank you for the changes!

**Pull request merged**
