### PR TITLE
Rename `enjoyed` to `used` when referring to past holidays

### PR DESCRIPTION
**Pull request by anarute**
Not every taken leave was really "enjoyed"/for pleasure

### CODE REVIEW

**Comment by joanmarie** [comment]
"Used" is a good choice. Thanks! :slightly_smiling_face:

**Review by jaragunde — CHANGES_REQUESTED** [review]
Thanks! But please, check the tasks page; there's another "enjoyed" there (which is now blank because it cannot find the corresponding tag in the results obtained from the server).

**Comment by anarute** [comment]
> Thanks! But please, check the tasks page; there's another "enjoyed" there (which is now blank because it cannot find the corresponding tag in the results obtained from the server).

I have changed [there](web/js/tasks.js) too, can you check if it can be cache on your browser?

**Review by jaragunde — APPROVED** [review]
My bad, sorry!

**Pull request merged**
