### PR TITLE
Properly minify holidayManagement.js.

### PR DESCRIPTION
**Pull request by jaragunde**
This was not being minified because the regexp didn't match.

We also tune a bit the `find` commands, to reduce the search scope.

### CODE REVIEW

**Comment by anarute** [comment]
Does the minification work with vuejs? I think we are getting errors, probably this mistake (using single quote instead of double quotes) was helping us 😅

**Comment by jaragunde** [comment]
Minification is not applied to vue files because those are excluded explicitly. Actually, they were using double quotes already!

```javascript
<script src="vuejs/vue.min.js"></script>
<script src="vuejs/v-calendar.2.3.2.min.js"></script>
```
How they are excluded in the Makefile:
```
	for i in `find web -name "*.js" -not -path "*web/vuejs/*"` ; do \
```

**Comment by anarute** [comment]
Sorry, I think I didn't express myself well: both holidayManagement.js and holidaySummary.js use new syntax that the current uglify version doesn't support:

```sh
/var/www/html/phpreport-beta
Parse error at holidayManagement.js:33,60
    rangeIdx = ranges.findIndex(range => range.coveredDates?.includes(day));
                                                            ^
ERROR: Unexpected token: punc «.»
    at JS_Parse_Error.get (eval at <anonymous> (/usr/share/nodejs/uglify-js/tools/node.js:18:1), <anonymous>:69:23)
    at fatal (/usr/share/nodejs/uglify-js/bin/uglifyjs:409:27)
    at run (/usr/share/nodejs/uglify-js/bin/uglifyjs:347:9)
    at Object.<anonymous> (/usr/share/nodejs/uglify-js/bin/uglifyjs:261:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
/var/www/html/phpreport-beta

Parse error at holidaySummary.js:121,37
            if (!event.relatedTarget?.classList.contains('autocompleteItemBtn'))
                                     ^
ERROR: Unexpected token: punc «.»
    at JS_Parse_Error.get (eval at <anonymous> (/usr/share/nodejs/uglify-js/tools/node.js:18:1), <anonymous>:69:23)
    at fatal (/usr/share/nodejs/uglify-js/bin/uglifyjs:409:27)
    at run (/usr/share/nodejs/uglify-js/bin/uglifyjs:347:9)
    at Object.<anonymous> (/usr/share/nodejs/uglify-js/bin/uglifyjs:261:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

So at the end, having them with single quotes were preventing us to have  broken minified files. I think we need either to upgrade the server version of uglify or ignore these files from being minified.

**Comment by jaragunde** [comment]
Ah! I didn't know about those errors because they don't happen in my development box. I have uglify 3.15. On the other hand, I found the problem reported in #585.

Let's keep this PR "on hold" for now.

**Comment by anarute** [comment]
The uglify version was upgraded in the host, it's safe to merge this one now. Thanks!

**Pull request merged**
