### PR TITLE
I357 new last date column in accumulated hours report

### PR DESCRIPTION
**Pull request by psaavedra**
* Added Last task date column in viewWorkingHoursResultsReport.php
* getExtraHoursReportService.php includes the lastTaskDate element
* Code formatting in getExtraHoursReportService.php

Related: #357

### CODE REVIEW

**Comment by psaavedra** [comment]
**pending action**: commit squashing.

**Comment by jaragunde** [comment]
Thanks for your patch, I've tested it. The dates returned by the web service via XML seem correct, but there is a problem when that date is parsed in the JS code: when printed in the grid, all the values are "today".

Also, the time is not necessary, I would format the dates like `dd/mm/yyyy`, to match the same format as the date selectors on top of the page.

**Comment by psaavedra** [comment]
Umm, I can't replicate this problem which you describe. In my local database the last_date column matches with the day of the latest task done during the dates interval. What am I missing?

**Comment by jaragunde** [comment]
Try this: create one task on Aug, 9 (yesterday) and another one on Aug, 10 (today). Then, go to the acc. hours report and set end date to Aug, 10 (or leave it blank for today). The expected "last task date" for that user is the 10 but it will say 9.

**Comment by psaavedra** [comment]
Ok. I see.

**Comment by jaragunde** [comment]
This is working properly now, and the "copy from yesterday" feature, which also uses `getLastTaskDate` works normally too. Proceeding to merge!

**Pull request merged**
