### PR TITLE
Improve user work summary at task panel 

### PR DESCRIPTION
**Pull request by pabelenda**
This implements the agreement we met at issue #341

### CODE REVIEW

**Comment by jaragunde** [comment]
I've found some issues:
* Decimal positions are not being trimmed, leading to bad-looking numbers like in the picture.
* Some data are presented in hours:minutes and other in hours with decimal positions. We should unify them. Let's implement hours:minutes and wait for user feedback.
* Finally, we had talked about renaming the fields to make them more explicit. See https://github.com/Igalia/phpreport/issues/341#issuecomment-369553360

screenshot from 2018-04-25 14-05-20

**Comment by pabelenda** [comment]
I've uploaded new changes.

I totally missed the field names. I thought the text inside parentheses was more like a clarification. The text are a bit large now, so I've added a bit of a tweak on the online css introduced at `web/js/tasks.js`.

I've treated timing more or less as done in the fields above. I've tested some cases and seems to be doing well.

**Comment by pabelenda** [comment]
* Added a pointer to the user documentation
* Reformated and added user documentation to cover new fields and be more readable

**Comment by jaragunde** [comment]
Results look great! Let's merge and wait for user feedback.

**Pull request merged**
