### PR TITLE
[#252] Add previous/next day buttons in Title panel header

### PR DESCRIPTION
**Pull request by tonythomas01**
selection_193

### CODE REVIEW

**Comment by pabelenda** [comment]
I've detected something:

1. Go to September 2nd
2. Move to the left until you reach August 31st
3. Move to the right

Expected result: To be on September 1st
Actual result: To be on October 2nd

4a. If you move again to the right you will be on September the 3rd.
4b. If you move again to the left, you will be on September 1st.

**Comment by tonythomas01** [comment]
Probably it was due to `addDate` adding in date irrespective of time, etc. 

changed to `addTime`, adding in `86400000`, which would do the trick.

**Comment by pabelenda** [comment]
It is working quite nice.

**Comment by pabelenda** [comment]
I've tested this.

addTime seems to work properly on day changes.

The day change using the arrow keys works nice as well.

**Comment by jaragunde** [comment]
I'm afraid the original wording in the issue was terrible! I don't think the buttons should be on every task, because changing the date is not an action belonging to the task, but to the page.

I was actually thinking on something like this:
screenshot from 2016-09-27 18-42-58

(The top bar with the date is actually coming from a different ticket, #115).
Would it be much work to remove the buttons from every task and add them to the bottom bar, like in the image above? Otherwise, I could merge the PR as it is; I'd prefer to merge it as it is rather than not having the feature :)

**Comment by tonythomas01** [comment]
The layout was changed after this PR, and we push the `new-task` thing to the center ?

**Comment by tonythomas01** [comment]
I would say making a panel above that original panel to show the date might seem a bit overkill. How about showing the date in something like `date: 28-09-2016`  on top of the left dock (user work summary?)

**Comment by jaragunde** [comment]
> I would say making a panel above that original panel to show the date might seem a bit overkill. How about showing the date in something like date: 28-09-2016 on top of the left dock (user work summary?)

That sounds good :) . We could still place the prev/next date buttons in the existing bar below the tasks. Imagine the situation where you are filling several days in a row; you could fill your tasks for a certain date and then jump to the next day to continue filling tasks, all using tab navigation.

**Comment by tonythomas01** [comment]
Adding an icong to button seems overkill, so I ended up here. How does it look ? 

selection_207

**Comment by jaragunde** [comment]
Just noticed the commit `[#252] Do not navigate while inputs or textarea in focus`, it contains two things: the part explained in the commit message and the addition of the next/prev buttons to the bottom bar. You should either split it or, at least, mention both things in the commit message.

**Comment by jaragunde** [comment]
Oh, this rebase mess seems to be easily fixable with another `git rebase -i master`, making sure your master is up to date. Remember to remove any commits that shouldn't be there, you should only leave the last three ones.

**Comment by jaragunde** [comment]
> Adding an icong to button seems overkill, so I ended up here. How does it look ?

Just to leave written testimony :) It looks good, we could just remove the arrow buttons in every task and make sure tab navigation lets users reach the buttons on the bottom. Then it would be ready to merge!

**Pull request merged**
