### PR TITLE
Fix a few PHP warnings

### PR DESCRIPTION
**Pull request by anarute**
Most of the issues were related to accessing an index from an empty array or null variable.

Tested locally with PHP 7.4.21

Related to #431

### CODE REVIEW

**Comment by jaragunde** [comment]
It looks great, thank you! Just one nit: the commit message in the second patch seems to be truncated... And, if you are going to reword past commit messages, maybe you could add "[#431]" to the first commit too! :innocent:

**Comment by anarute** [comment]
> It looks great, thank you! Just one nit: the commit message in the second patch seems to be truncated... And, if you are going to reword past commit messages, maybe you could add "[#431]" to the first commit too! 😇

@jaragunde thank you for the quick review :) commits fixed!

Btw I had to rename the INSTALL file because I was in a very weird loop: I restored it and git deleted the install folder, if I restore the folder it deleted the file 😅  probably because they had the same name.

I had to add this change to this PR because I wasn't being able to rebase due to this (https://github.com/Igalia/phpreport/pull/502/commits/f7bafec45611b34d6477ba33335bab82c90b274e) but let me know if you prefer me to create a PR for it

**Comment by jaragunde** [comment]
> Btw I had to rename the INSTALL file because I was in a very weird loop: I restored it and git deleted the install folder, if I restore the folder it deleted the file sweat_smile probably because they had the same name.
> 

Oh, maybe a file system limitation. Yes, it's a good idea to rename and have different names for the file and the folder, they could cause trouble somewhere else (Windows, too?).

**Comment by anarute** [comment]
> > Btw I had to rename the INSTALL file because I was in a very weird loop: I restored it and git deleted the install folder, if I restore the folder it deleted the file sweat_smile probably because they had the same name.
> 
> Oh, maybe a file system limitation. Yes, it's a good idea to rename and have different names for the file and the folder, they could cause trouble somewhere else (Windows, too?).

And that's how I just found out that MacOS file system is case-insensitive by default 😬 

Btw added a new commit to fix a warning I just found

**Comment by anarute** [comment]
FYI added a few more fixes since the last you've reviewed. I don't  intend to change this branch anymore, I'll create new PRs if I find new issues

**Review by jaragunde — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
