### PR TITLE
[#389] Add a button to fill a full holiday

### PR DESCRIPTION
**Pull request by pabelenda**
Button added. Tested on a local deployment.

It will probably require some revision of the configuration files of the specific deployments, should we warn this somehow?

### CODE REVIEW

**Comment by jaragunde** [comment]
I'm finding trouble with this patch. The task record gets created in a strange way, and the `createTask` call contains wrong information for project id:
```
<projectId>ext-record-644</projectId>
```

**Comment by jaragunde** [comment]
Also, check the indentation in `tasks.php`, the existing code is indented with spaces but you used tabs.

**Comment by jaragunde** [comment]
Let's not put the focus in the project field after the task is created, it's confusing.

**Comment by jaragunde** [comment]
Also, an enhancement: let's save the task immediately after it's created! The trigger for auto save is 10 seconds, so if you want to fill e.g. one or two weeks of holidays in a row, it can be a bit annoying to wait 10 seconds (or manually save) every time.

**Comment by pabelenda** [comment]
* Checked indentation for `tasks.php`
* Avoided focus set. It will remain in the button
* Added save logic. Fired it after 100 ms. Doing it straight away was failing.

**Comment by jaragunde** [comment]
Now, the UI is reporting an error immediately before saving the task. There can even be several error messages if you created and deleted some tasks before:
* Create a task and save it.
* Delete the task, don't save yet.
* Create a holiday task with the "full holiday-task" button.
You will see several error messages. If you now delete the holiday task and then press the "full holiday-task" button again, the number of errors increases.

**Comment by jaragunde** [comment]
`window.setInterval` will create a permanent callback that runs every 100 ms. Every time you press the button, a new callback is created, and they all step into each other's toes. Even with 100ms, chances are that the save operation is being called once again before the response arrives back, that's why there is an error message followed by the save confirmation.

**Comment by jaragunde** [comment]
To run the save code snippet only once after 100ms, you can use `setTimeout`: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout

**Comment by pabelenda** [comment]
Indeed `setInterval` is much more convenient.

**Comment by jaragunde** [comment]
I'm still getting a validation error on the first save attempt. If I delay the timeout to 500ms, it works correctly. I think the problem here is the validation code, which doesn't properly run when the widgets of the task box are not ready.

Let's move forward with a higher timeout. We may need to adjust it for real deployments, widgets like the projects combo box may take longer to setup due to higher server latency.

**Pull request merged**
