### PR TITLE
caldav: add email for calendar user

### PR DESCRIPTION
**Pull request by anarute**
Currently our username and email don't match so if these values
are different the calendar event won't be displayed in the user's
calendar.

### CODE REVIEW

**Comment by jaragunde** [comment]
It makes sense not building up email addresses like we did there, but does that really fix the problem you describe? What if an individual user's email and username + domain don't match?

**Comment by anarute** [comment]
> It makes sense not building up email addresses like we did there, but does that really fix the problem you describe? What if an individual user's email and username + domain don't match?

That's a good point, I think the event wouldn't show up for the user. But in that case the best way to fix this in my opinion is to start storing the user email in PhpReport as well: #434

**Comment by anarute** [comment]
@jaragunde gentle ping about this one :)

**Review by jaragunde — APPROVED** [review]
Sorry I forgot. Yeah, it's a positive change, let's land it.

**Pull request merged**
