### PR TITLE
Fixes in email warning

### PR DESCRIPTION
**Pull request by anarute**
- Fix how to fetch days without tasks
- Ignore users with journeys of 0 hours

### CODE REVIEW

**Review by dmtrek14 — APPROVED** [review]
Looks good to me!

**Review by jaragunde — APPROVED** [review]
I ran it on my test data and found it used to report the list of empty days incorrectly for one user, and now it's fixed. Thanks!

A nit, I noticed a mismatch between the code and the template, one says `###LIST_OF_DATES###` and the other says `###LIST_OF_EMPTY_DAYS###`.

**Comment by anarute** [comment]
> I ran it on my test data and found it used to report the list of empty days incorrectly for one user, and now it's fixed. Thanks!
> 
> A nit, I noticed a mismatch between the code and the template, one says `###LIST_OF_DATES###` and the other says `###LIST_OF_EMPTY_DAYS###`.

Good catch, thank you for noticing.

**Review by jaragunde — APPROVED** [review]
Still looking good!

**Pull request merged**
